Update ipcw.py
Error: AttributeError: module 'scipy.integrate' has no attribute 'simps'  
Reason:  
In SciPy v1.5.4, `scipy.integrate.simps` was used.  
In SciPy v1.16.0, it's replaced with `scipy.integrate.simpson`.